service: createimage
frameworkVersion: '3'

provider:
  name: aws
  runtime: java25
  region: eu-central-1
  timeout: 10
  memorySize: 1024
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::${self:custom.thumbnailBucket}/*'
            - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

package:
  artifact: target/Familienkalender-Server-1.0-SNAPSHOT-shaded.jar

functions:
  FamilyWall-Kalender:
    handler: de.goForFun.familienkalender.CreateKalenderImage
    environment:
      THUMBNAIL_SIZE: 100